name: Tests

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/tests.yml
    - shodo/**
    - tests/**
  pull_request:
    paths:
    - .github/workflows/tests.yml
    - shodo/**
    - tests/**

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    name: Python ${{ matrix.python-version }} tests

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -e ".[dev]"

    - name: Run tests
      run: pytest tests/
